config/routes.rb
Rails.application.routes.draw do

   root 'persons#index'
   resources :persons

end

app/models/person.rb
class Person < ActiveRecord::Base
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
	def index
		# @person = Persons.all
	end

	def new
		@person = Person.new
	end

	def create
		@person = Person.new(:first_name=>params[:person][:first_name],:last_name=>params[:person][:last_name],:city=>params[:person][:city],:state=>params[:person][:state])
		@person.save
	end

	def show

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Persons</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/persons/index.html.erb
<html>
<head>
<title>mydetails</title>
</head>
<body>
welcome to my details
<%=link_to "click",new_person_path%>
</body>
</html>

app/views/persons/new.html.erb
 <html>
 <body>
 <%=form_for @person do |p|%>

  <div class="form-group">
  <%=p.label :firstname%>
 <%=p.text_field :first_name%>
  </div>

<div class="form-group">
  <%=p.label :lastname%>
  <%=p.text_field :last_name%>
  </div>

  <div class="form-group">
  <%=p.label :city%>
  <%=p.text_field :city%>
  </div>

  <div class="form-group">
  <%=p.label :state%>
  <%=p.text_field :state%>
  </div>



  <%=p.submit "submit"%>
  <%end%>  
  </body>
  </html>